# Generated by Django 5.0.7 on 2024-07-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(null=True)),
                ("price", models.FloatField()),
                ("marketers", models.ManyToManyField(blank=True, to="users.marketer")),
            ],
        ),
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(null=True)),
                ("price", models.FloatField(blank=True)),
                ("customers", models.ManyToManyField(blank=True, to="users.customer")),
                ("products", models.ManyToManyField(blank=True, to="main.product")),
            ],
        ),
    ]
