# Generated by Django 5.0.7 on 2024-07-30 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
        ("users", "0002_remove_customer_d_o_b_remove_customer_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="product",
            name="target",
            field=models.CharField(
                choices=[
                    ("B2B", "Business to Business Marketing"),
                    ("B2C", "Business to Customer Marketing"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    (1, "Branding and Identity Services"),
                    (2, "Marketing and Advertising Services"),
                    (3, "Content Creation and Strategy"),
                    (4, "E-Commerce Solutions"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscribe",
            name="subscribe_id",
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.FloatField(blank=True),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_id", models.CharField(max_length=10, null=True, unique=True)),
                ("total", models.FloatField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.product",
                    ),
                ),
                (
                    "subscribe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.subscribe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=15, null=True, unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.FloatField(blank=True)),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.cart",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.customer",
                    ),
                ),
            ],
        ),
    ]
