# Generated by Django 5.0.7 on 2024-07-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketer",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.customer",
            ),
        ),
    ]
