# Generated by Django 5.0.7 on 2024-07-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_product_product_id_product_target_product_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(blank=True, to="main.product"),
        ),
    ]
