# Generated by Django 5.0.7 on 2024-07-26 06:48

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_marketer_customer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="d_o_b",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="profile_image",
            field=models.ImageField(null=True, upload_to=main.models.rename_image),
        ),
        migrations.AddField(
            model_name="customer",
            name="title",
            field=models.CharField(
                choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Ms", "Ms")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="marketer",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketer",
            name="title",
            field=models.CharField(
                choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Ms", "Ms")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="marketer",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
