# Generated by Django 5.0.7 on 2024-07-30 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="d_o_b",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="title",
        ),
        migrations.RemoveField(
            model_name="marketer",
            name="d_o_b",
        ),
        migrations.RemoveField(
            model_name="marketer",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="marketer",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="marketer",
            name="title",
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="marketer",
            name="staff_id",
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Ms", "Ms")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("d_o_b", models.DateField(null=True)),
                ("phone", models.PositiveBigIntegerField(null=True, unique=True)),
                ("is_customer", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
